# PulseAudio daemon settings for SFML Playground Container
default-sample-format = s16le
default-sample-rate = 44100
default-sample-channels = 2
exit-idle-time = -1
flat-volumes = no
high-priority = no
realtime-scheduling = no
daemonize = yes
